# Site settings
author: Erman 
title: LarryVsWeb
header-img: img/home-bg.png
email: ermanbekaroglu@gmail.com
copyright_name: Erman 
description: > # this means to ignore newlines until "baseurl:"
  Various Web Projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  larryvsdata

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
